version = 3.10.0
runner.dialect = scala3
style = default
rewrite.scala3.convertToNewSyntax = true

maxColumn = 140

rewrite.rules = [
  AvoidInfix
  RedundantBraces
  RedundantParens
  AsciiSortImports
  PreferCurlyFors
]

fileOverride {
  "glob:**.sbt" {
    runner.dialect = sbt1
    rewrite.scala3.convertToNewSyntax = false
  }
}

project.excludePaths = ["glob:**/codegentests/**/*.scala"]
